networks:
  anime-network:
    name: anime-network
    external: true

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anime
      MYSQL_USER: anime
      MYSQL_PASSWORD: anime
    volumes:
      - /opt/docker/anime/mysql:/var/lib/mysql:delegated
    networks:
      - anime-network
    ports:
      - "8952:3306"
    restart: unless-stopped
